version: "3.9"
services:
  feeder:
    image: pizaini/feeder-pddikti:22.2
    container_name: feeder
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: prod
    volumes:
      - /home/pizaini/docker-volume/feeder-neo/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/pizaini/docker-volume/feeder-neo/prefill_pddikti:/prefill_pddikti
    ports:
      - "8100:8100"
      - "3003:3003"
  db-pddikti:
    image: postgres:12
    container_name: dbpddikti
    restart: unless-stopped
    tty: true
    ports:
      - "54333:54333"
    volumes:
      - /home/pizaini/docker-volume/feeder-neo/pgsql/data:/var/lib/postgresql/data